//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncidentDetection.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IncidentDetection.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Number.
        /// </summary>
        public static string AddNum {
            get {
                return ResourceManager.GetString("AddNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a custom emergency contact.
        /// </summary>
        public static string AddNumDesc {
            get {
                return ResourceManager.GetString("AddNumDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Number.
        /// </summary>
        public static string AddNumTitle {
            get {
                return ResourceManager.GetString("AddNumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling permission is needed to call emergency services if nobody responds.
        /// </summary>
        public static string CallPermission {
            get {
                return ResourceManager.GetString("CallPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call emergency services on no response?.
        /// </summary>
        public static string CallSwitch {
            get {
                return ResourceManager.GetString("CallSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to cancel emergency call:.
        /// </summary>
        public static string CancelCallTime {
            get {
                return ResourceManager.GetString("CancelCallTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Countdown.
        /// </summary>
        public static string CancelCountdown {
            get {
                return ResourceManager.GetString("CancelCountdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to cancel emergency:.
        /// </summary>
        public static string CancelTime {
            get {
                return ResourceManager.GetString("CancelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose contact numbers.
        /// </summary>
        public static string ChooseNums {
            get {
                return ResourceManager.GetString("ChooseNums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Contacts.
        /// </summary>
        public static string ContactList {
            get {
                return ResourceManager.GetString("ContactList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  seconds until help is notified!.
        /// </summary>
        public static string Countdown {
            get {
                return ResourceManager.GetString("Countdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  seconds until emergency services are called!.
        /// </summary>
        public static string CountdownEmergency {
            get {
                return ResourceManager.GetString("CountdownEmergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to Defaults.
        /// </summary>
        public static string Defaults {
            get {
                return ResourceManager.GetString("Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident Detected!!.
        /// </summary>
        public static string DetectedMsg {
            get {
                return ResourceManager.GetString("DetectedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Emergency Contacts.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Contact List.
        /// </summary>
        public static string EmergencyList {
            get {
                return ResourceManager.GetString("EmergencyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Number:.
        /// </summary>
        public static string EmergencyNum {
            get {
                return ResourceManager.GetString("EmergencyNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will send a message to your emergency contacts asking for help. Continue?.
        /// </summary>
        public static string HelpDesc {
            get {
                return ResourceManager.GetString("HelpDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location permission is needed to send your location in the event of an incident.
        /// </summary>
        public static string LocationPermission {
            get {
                return ResourceManager.GetString("LocationPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an automated message from my incident detection app. An incident has been detected at.
        /// </summary>
        public static string Message1 {
            get {
                return ResourceManager.GetString("Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If no contact responds within.
        /// </summary>
        public static string MessageCall1 {
            get {
                return ResourceManager.GetString("MessageCall1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds then emergency services will be called.
        /// </summary>
        public static string MessageCall2 {
            get {
                return ResourceManager.GetString("MessageCall2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Speed to trigger sensor readings (m/s):.
        /// </summary>
        public static string MinSpeed {
            get {
                return ResourceManager.GetString("MinSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify audio permission is needed to play a prerecorded message during the call to emergency services if nobody responds.
        /// </summary>
        public static string ModifyAudioPermission {
            get {
                return ResourceManager.GetString("ModifyAudioPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for collisions to keep you safe.
        /// </summary>
        public static string NotificationDesc {
            get {
                return ResourceManager.GetString("NotificationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident Detection.
        /// </summary>
        public static string NotificationTitle {
            get {
                return ResourceManager.GetString("NotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help has been notified!.
        /// </summary>
        public static string Notified {
            get {
                return ResourceManager.GetString("Notified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency services have been notified!.
        /// </summary>
        public static string NotifiedCall {
            get {
                return ResourceManager.GetString("NotifiedCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send I&apos;m Okay.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkBtn {
            get {
                return ResourceManager.GetString("OkBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a message from my incident detection app. I&apos;m alright and no further help is needed..
        /// </summary>
        public static string OkMessage {
            get {
                return ResourceManager.GetString("OkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive sms permission is needed to know if an emergency contact responded.
        /// </summary>
        public static string ReceiveSMSPermission {
            get {
                return ResourceManager.GetString("ReceiveSMSPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Settings?.
        /// </summary>
        public static string ResetTitle {
            get {
                return ResourceManager.GetString("ResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will send a message to your emergency contacts notifying them that you are alright. Continue?.
        /// </summary>
        public static string SendOKDesc {
            get {
                return ResourceManager.GetString("SendOKDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send OK?.
        /// </summary>
        public static string SendOKTitle {
            get {
                return ResourceManager.GetString("SendOKTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detection Sensitivity:.
        /// </summary>
        public static string Sensitivity {
            get {
                return ResourceManager.GetString("Sensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (bike).
        /// </summary>
        public static string SensitivityBike {
            get {
                return ResourceManager.GetString("SensitivityBike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (car).
        /// </summary>
        public static string SensitivityCar {
            get {
                return ResourceManager.GetString("SensitivityCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (falls).
        /// </summary>
        public static string SensitivityFalls {
            get {
                return ResourceManager.GetString("SensitivityFalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS permission is needed to send your location in the event of an incident.
        /// </summary>
        public static string SMSPermission {
            get {
                return ResourceManager.GetString("SMSPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS message failed to send.
        /// </summary>
        public static string SMSSentFail {
            get {
                return ResourceManager.GetString("SMSSentFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS message sent.
        /// </summary>
        public static string SMSSentOk {
            get {
                return ResourceManager.GetString("SMSSentOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident detection enabled:.
        /// </summary>
        public static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident Detection App.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (You must enter a valid number!).
        /// </summary>
        public static string ValidNum {
            get {
                return ResourceManager.GetString("ValidNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrate permission is needed to alert you before sending SOS messages.
        /// </summary>
        public static string VibratePermission {
            get {
                return ResourceManager.GetString("VibratePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesBtn {
            get {
                return ResourceManager.GetString("YesBtn", resourceCulture);
            }
        }
    }
}
